// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASqPO5Wa06dbR1-L_M5yV4gko7A85wjw0',
    appId: '1:993426116499:web:3fb546bad53be075846266',
    messagingSenderId: '993426116499',
    projectId: 'doctorappointmentappdatabase',
    authDomain: 'doctorappointmentappdatabase.firebaseapp.com',
    storageBucket: 'doctorappointmentappdatabase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Bjq5kq232c7_XrHLLFurEV6V4O6AciM',
    appId: '1:993426116499:android:488ffccb0ef9acae846266',
    messagingSenderId: '993426116499',
    projectId: 'doctorappointmentappdatabase',
    storageBucket: 'doctorappointmentappdatabase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTUNIh07HfW6O8MbxkqrcIkTm-efiiGaU',
    appId: '1:409599515475:ios:a79cb24f70b799a3b2dfa6',
    messagingSenderId: '409599515475',
    projectId: 'doctorappointmentapp-830bb',
    storageBucket: 'doctorappointmentapp-830bb.firebasestorage.app',
    iosBundleId: 'com.example.flutterProyectoU2Front',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTUNIh07HfW6O8MbxkqrcIkTm-efiiGaU',
    appId: '1:409599515475:ios:a79cb24f70b799a3b2dfa6',
    messagingSenderId: '409599515475',
    projectId: 'doctorappointmentapp-830bb',
    storageBucket: 'doctorappointmentapp-830bb.firebasestorage.app',
    iosBundleId: 'com.example.flutterProyectoU2Front',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASqPO5Wa06dbR1-L_M5yV4gko7A85wjw0',
    appId: '1:993426116499:web:5babeb4094b42235846266',
    messagingSenderId: '993426116499',
    projectId: 'doctorappointmentappdatabase',
    authDomain: 'doctorappointmentappdatabase.firebaseapp.com',
    storageBucket: 'doctorappointmentappdatabase.firebasestorage.app',
  );

}