// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGZ0lsjpFQRTziWkngXA5GqTzvkKkwgGY',
    appId: '1:409599515475:web:ea92fabf7e375b56b2dfa6',
    messagingSenderId: '409599515475',
    projectId: 'doctorappointmentapp-830bb',
    authDomain: 'doctorappointmentapp-830bb.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-830bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvdnoczpKaUJAkSLHQiVZEnud-X_hEfHE',
    appId: '1:409599515475:android:3ced8fbce758d0cdb2dfa6',
    messagingSenderId: '409599515475',
    projectId: 'doctorappointmentapp-830bb',
    storageBucket: 'doctorappointmentapp-830bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTUNIh07HfW6O8MbxkqrcIkTm-efiiGaU',
    appId: '1:409599515475:ios:a79cb24f70b799a3b2dfa6',
    messagingSenderId: '409599515475',
    projectId: 'doctorappointmentapp-830bb',
    storageBucket: 'doctorappointmentapp-830bb.firebasestorage.app',
    iosBundleId: 'com.example.flutterProyectoU2Front',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTUNIh07HfW6O8MbxkqrcIkTm-efiiGaU',
    appId: '1:409599515475:ios:a79cb24f70b799a3b2dfa6',
    messagingSenderId: '409599515475',
    projectId: 'doctorappointmentapp-830bb',
    storageBucket: 'doctorappointmentapp-830bb.firebasestorage.app',
    iosBundleId: 'com.example.flutterProyectoU2Front',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGZ0lsjpFQRTziWkngXA5GqTzvkKkwgGY',
    appId: '1:409599515475:web:27ddd705d929256fb2dfa6',
    messagingSenderId: '409599515475',
    projectId: 'doctorappointmentapp-830bb',
    authDomain: 'doctorappointmentapp-830bb.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-830bb.firebasestorage.app',
  );
}
